# Generated by Django 5.0.4 on 2024-06-24 21:17

import django.core.validators
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=70, validators=[student.models.validate_no_digit_and_special_characters])),
                ('last_name', models.CharField(max_length=70, validators=[student.models.validate_no_digit_and_special_characters])),
                ('mobile_number', models.CharField(max_length=10, unique=True, validators=[student.models.validate_mobile_number_length])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(3, message='Address must be at least 3 characters long.'), django.core.validators.MaxLengthValidator(500, message='Address cannot exceed 500 characters.')])),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
